version: "3"

services:
    db:
        volumes:
            - ./data:/var/lib/postgresql/data

    backend:
        command: poetry run ./manage.py runserver
        volumes:
            - .:/app

    proxy:
        volumes:
          - ./conf/nginx-dev.conf:/etc/nginx/nginx.conf
