# Generated by Django 5.0.2 on 2024-03-31 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "tests",
            "0004_rename_score_a_menudo_preguntalikertnoas_puntaje_a_menudo_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloqueo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("motivo", models.TextField()),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disponibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=9,
                        verbose_name="día",
                    ),
                ),
                (
                    "hora_inicio",
                    models.IntegerField(
                        choices=[
                            (0, "0 AM"),
                            (1, "1 AM"),
                            (2, "2 AM"),
                            (3, "3 AM"),
                            (4, "4 AM"),
                            (5, "5 AM"),
                            (6, "6 AM"),
                            (7, "7 AM"),
                            (8, "8 AM"),
                            (9, "9 AM"),
                            (10, "10 AM"),
                            (11, "11 AM"),
                            (12, "12 PM"),
                            (13, "1 PM"),
                            (14, "2 PM"),
                            (15, "3 PM"),
                            (16, "4 PM"),
                            (17, "5 PM"),
                            (18, "6 PM"),
                            (19, "7 PM"),
                            (20, "8 PM"),
                            (21, "9 PM"),
                            (22, "10 PM"),
                            (23, "11 PM"),
                        ]
                    ),
                ),
                (
                    "minuto_inicio",
                    models.IntegerField(
                        choices=[(0, "00"), (15, "15"), (30, "30"), (45, "45")]
                    ),
                ),
                (
                    "hora_fin",
                    models.IntegerField(
                        choices=[
                            (0, "0 AM"),
                            (1, "1 AM"),
                            (2, "2 AM"),
                            (3, "3 AM"),
                            (4, "4 AM"),
                            (5, "5 AM"),
                            (6, "6 AM"),
                            (7, "7 AM"),
                            (8, "8 AM"),
                            (9, "9 AM"),
                            (10, "10 AM"),
                            (11, "11 AM"),
                            (12, "12 PM"),
                            (13, "1 PM"),
                            (14, "2 PM"),
                            (15, "3 PM"),
                            (16, "4 PM"),
                            (17, "5 PM"),
                            (18, "6 PM"),
                            (19, "7 PM"),
                            (20, "8 PM"),
                            (21, "9 PM"),
                            (22, "10 PM"),
                            (23, "11 PM"),
                        ]
                    ),
                ),
                (
                    "minuto_fin",
                    models.IntegerField(
                        choices=[(0, "00"), (15, "15"), (30, "30"), (45, "45")]
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_disponibles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "entrevistado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entrevistas",
                        to="tests.persona",
                    ),
                ),
                (
                    "entrevistador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entrevistas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
