# Generated by Django 5.0.2 on 2024-04-02 01:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entrevistas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disponibilidad",
            options={"verbose_name_plural": "disponibilidades"},
        ),
    ]
