# Generated by Django 5.0.2 on 2024-04-02 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrevistas", "0002_alter_disponibilidad_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloqueo",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="disponibilidad",
            name="usuario",
        ),
        migrations.CreateModel(
            name="Entrevistador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="entrevistador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bloqueo",
            name="entrevistador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloqueos",
                to="entrevistas.entrevistador",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disponibilidad",
            name="entrevistador",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios_disponibles",
                to="entrevistas.entrevistador",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="entrevista",
            name="entrevistador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="entrevistas",
                to="entrevistas.entrevistador",
            ),
        ),
    ]
