# Generated by Django 5.0.2 on 2024-04-05 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "entrevistas",
            "0003_remove_bloqueo_usuario_remove_disponibilidad_usuario_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entrevistador",
            options={"verbose_name_plural": "entrevistadores"},
        ),
    ]
