# Generated by Django 5.0.2 on 2024-04-05 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrevistas", "0004_alter_entrevistador_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrevista",
            old_name="fecha",
            new_name="fecha_inicio",
        ),
        migrations.AddField(
            model_name="entrevista",
            name="fecha_fin",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 5, 9, 5, 8, 678876)
            ),
            preserve_default=False,
        ),
    ]
