# Generated by Django 5.0.2 on 2024-05-01 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrevistas", "0005_rename_fecha_entrevista_fecha_inicio_and_more"),
        (
            "tests",
            "0004_rename_score_a_menudo_preguntalikertnoas_puntaje_a_menudo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrevista",
            name="entrevistado",
        ),
        migrations.AddField(
            model_name="entrevista",
            name="acceso",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="entrevistas",
                to="tests.accesotestpersona",
            ),
            preserve_default=False,
        ),
    ]
