# Generated by Django 5.0.2 on 2024-05-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrevistas", "0006_remove_entrevista_entrevistado_entrevista_acceso"),
        ("tests", "0006_alter_tramocategoriaevaluacion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrevista",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="entrevista",
            name="resultado",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="entrevistas",
                to="tests.resultado",
            ),
        ),
    ]
