# Generated by Django 5.0.2 on 2024-05-12 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrevistas", "0007_entrevista_observaciones_entrevista_resultado"),
        ("tests", "0008_resultado_informe_alter_resultado_acceso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrevista",
            name="resultado",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="entrevista",
                to="tests.resultado",
            ),
        ),
    ]
