# Generated by Django 5.0.2 on 2024-06-02 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrevistas", "0010_alter_sicologo_options_sicologo_firma_and_more"),
        ("tests", "0014_alter_resultadoevaluacion_texto"),
    ]

    operations = [
        migrations.AddField(
            model_name="entrevista",
            name="resultado_entrevista",
            field=models.ForeignKey(
                blank=True,
                help_text="Si se indica un valor, este tiene precedencia sobre el resultado del test.",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="entrevistas",
                to="tests.resultadoevaluacion",
            ),
        ),
    ]
