# Generated by Django 5.0.2 on 2024-06-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("entrevistas", "0011_entrevista_resultado_entrevista"),
    ]

    operations = [
        migrations.AddField(
            model_name="sicologo",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino")],
                default="M",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sicologo",
            name="titulo",
            field=models.CharField(
                default="Psicólogo",
                help_text="Ej: Psicólogo Clínico",
                max_length=100,
                verbose_name="título",
            ),
            preserve_default=False,
        ),
    ]
