# Generated by Django 5.0.2 on 2024-03-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="evaluacion",
            field=models.JSONField(null=True),
        ),
    ]
