# Generated by Django 5.0.2 on 2024-03-10 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0002_resultado_evaluacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="uuid4",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="entrevista",
            name="resultado",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="entrevista",
                to="informes.resultado",
            ),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="informe",
            field=models.FileField(null=True, upload_to="informes/%Y/%m/%d/"),
        ),
    ]
