# Generated by Django 5.0.2 on 2024-03-10 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0003_resultado_uuid4_alter_entrevista_resultado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entrevista",
            name="entrevistador",
        ),
    ]
