# Generated by Django 5.0.2 on 2024-03-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0004_remove_entrevista_entrevistador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entrevista",
            name="plataforma",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("zoom", "Zoom"),
                    ("meet", "Google Meet"),
                ],
                max_length=255,
            ),
        ),
    ]
