# Generated by Django 5.0.2 on 2024-03-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("informes", "0005_alter_entrevista_plataforma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultado",
            name="uuid4",
        ),
        migrations.AddField(
            model_name="resultado",
            name="clave_archivo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
