# Generated by Django 5.0.2 on 2024-03-23 02:48

import django.db.models.deletion
import django_countries.fields
import tests.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rut",
                    tests.models.RUTField(
                        max_length=12, unique=True, verbose_name="RUT"
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        max_length=100, verbose_name="nombres o razón social"
                    ),
                ),
                (
                    "es_natural",
                    models.BooleanField(
                        default=True, verbose_name="es persona natural"
                    ),
                ),
                ("apellido_paterno", models.CharField(blank=True, max_length=100)),
                ("apellido_materno", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "nacionalidad",
                    django_countries.fields.CountryField(blank=True, max_length=2),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona_juridica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos",
                        to="tests.persona",
                    ),
                ),
                (
                    "persona_natural",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empresas",
                        to="tests.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccesoTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(verbose_name="fecha de vencimiento"),
                ),
                (
                    "mandante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesos_mandante",
                        to="tests.persona",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesos",
                        to="tests.test",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "acceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="tests.accesotest",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="tests.persona",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="tests.test",
                    ),
                ),
            ],
            options={
                "unique_together": {("persona", "test")},
            },
        ),
        migrations.CreateModel(
            name="PreguntaLikertNOAS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "score_nunca",
                    models.IntegerField(default=1, verbose_name="Nunca o casi nunca"),
                ),
                (
                    "score_ocasionalmente",
                    models.IntegerField(default=2, verbose_name="Ocasionalmente"),
                ),
                (
                    "score_a_menudo",
                    models.IntegerField(default=3, verbose_name="A menudo"),
                ),
                (
                    "score_siempre",
                    models.IntegerField(
                        default=4, verbose_name="Siempre o casi siempre"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tests.test"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccesoTestPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                (
                    "acceso_test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ruts",
                        to="tests.accesotest",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="accesos",
                        to="tests.persona",
                    ),
                ),
            ],
            options={
                "unique_together": {("acceso_test", "persona")},
            },
        ),
        migrations.CreateModel(
            name="RespuestaLikertNOAS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alternativa",
                    models.CharField(
                        choices=[
                            ("N", "Nunca o casi nunca"),
                            ("O", "Ocasionalmente"),
                            ("A", "A menudo"),
                            ("S", "Siempre o casi siempre"),
                        ],
                        max_length=1,
                    ),
                ),
                ("score", models.IntegerField()),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="tests.preguntalikertnoas",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tests.resultado",
                    ),
                ),
            ],
            options={
                "unique_together": {("resultado", "pregunta")},
            },
        ),
    ]
