# Generated by Django 5.0.2 on 2024-03-24 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0003_accesotest_valor_unitario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preguntalikertnoas",
            old_name="score_a_menudo",
            new_name="puntaje_a_menudo",
        ),
        migrations.RenameField(
            model_name="preguntalikertnoas",
            old_name="score_nunca",
            new_name="puntaje_nunca",
        ),
        migrations.RenameField(
            model_name="preguntalikertnoas",
            old_name="score_ocasionalmente",
            new_name="puntaje_ocasionalmente",
        ),
        migrations.RenameField(
            model_name="preguntalikertnoas",
            old_name="score_siempre",
            new_name="puntaje_siempre",
        ),
        migrations.RenameField(
            model_name="respuestalikertnoas",
            old_name="score",
            new_name="puntaje",
        ),
        migrations.AlterUniqueTogether(
            name="resultado",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="acceso",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados",
                to="tests.accesotestpersona",
            ),
        ),
        migrations.RemoveField(
            model_name="resultado",
            name="persona",
        ),
        migrations.RemoveField(
            model_name="resultado",
            name="test",
        ),
    ]
