# Generated by Django 5.0.2 on 2024-05-11 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tests",
            "0004_rename_score_a_menudo_preguntalikertnoas_puntaje_a_menudo_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TramoCategoriaEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("COGNITIVA", "Cognitiva"),
                            ("MOTORA", "Motora"),
                            ("NO_PLANIFICADA", "No planificada"),
                        ],
                        max_length=100,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("texto", models.TextField(verbose_name="texto")),
                ("puntaje_minimo", models.IntegerField(verbose_name="puntaje mínimo")),
                ("puntaje_maximo", models.IntegerField(verbose_name="puntaje máximo")),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tramos",
                        to="tests.test",
                    ),
                ),
            ],
            options={
                "unique_together": {("test", "categoria", "nombre")},
            },
        ),
    ]
