# Generated by Django 5.0.2 on 2024-05-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0005_tramocategoriaevaluacion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tramocategoriaevaluacion",
            options={
                "verbose_name": "Tramo de categoría de evaluación",
                "verbose_name_plural": "Tramos de categorías de evaluación",
            },
        ),
        migrations.AddField(
            model_name="resultado",
            name="clave_archivo",
            field=models.CharField(default=123456789012, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resultado",
            name="evaluacion",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="preguntalikertnoas",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("COGNITIVA", "Cognitiva"),
                    ("MOTORA", "Motora"),
                    ("NO_PLANIFICADA", "No planificada"),
                ],
                max_length=20,
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="preguntalikertnoas",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas_%(class)s",
                to="tests.test",
            ),
        ),
        migrations.AlterField(
            model_name="respuestalikertnoas",
            name="resultado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas_%(class)s",
                to="tests.resultado",
            ),
        ),
        migrations.AlterField(
            model_name="tramocategoriaevaluacion",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General"),
                    ("COGNITIVA", "Cognitiva"),
                    ("MOTORA", "Motora"),
                    ("NO_PLANIFICADA", "No planificada"),
                ],
                max_length=100,
                verbose_name="categoría",
            ),
        ),
        migrations.AlterField(
            model_name="tramocategoriaevaluacion",
            name="nombre",
            field=models.CharField(
                choices=[("BAJO", "Bajo"), ("MODERADO", "Moderado"), ("ALTO", "Alto")],
                max_length=100,
            ),
        ),
    ]
