# Generated by Django 5.0.2 on 2024-05-12 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0006_alter_tramocategoriaevaluacion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preguntalikertnoas",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tests.test"
            ),
        ),
        migrations.AlterField(
            model_name="respuestalikertnoas",
            name="resultado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tests.resultado"
            ),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="clave_archivo",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="evaluacion",
            field=models.JSONField(default=dict),
        ),
    ]
