# Generated by Django 5.0.2 on 2024-05-12 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0007_alter_preguntalikertnoas_test_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="informe",
            field=models.FileField(null=True, upload_to="resultados/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="acceso",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultado",
                to="tests.accesotestpersona",
            ),
        ),
    ]
