# Generated by Django 5.0.2 on 2024-05-12 03:26

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0008_resultado_informe_alter_resultado_acceso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gentilicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pais",
                    django_countries.fields.CountryField(max_length=2, unique=True),
                ),
                ("gentilicio", models.CharField(max_length=100)),
            ],
        ),
    ]
