# Generated by Django 5.0.2 on 2024-06-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0010_alter_gentilicio_gentilicio"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesotestpersona",
            name="fin_respuestas_ts",
            field=models.DateTimeField(null=True, verbose_name="término test"),
        ),
        migrations.AddField(
            model_name="accesotestpersona",
            name="inicio_respuestas_ts",
            field=models.DateTimeField(null=True, verbose_name="inicio test"),
        ),
    ]
