# Generated by Django 5.0.2 on 2024-06-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0011_accesotestpersona_fin_respuestas_ts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesotest",
            name="cargo_predefinido",
            field=models.CharField(
                choices=[
                    ("NOCHERO", "Nochero"),
                    ("RONDIN", "Rondín"),
                    ("PORTERO", "Portero"),
                    ("CONSERJE", "Conserje"),
                    ("VIGILANTE_PRIVADO", "Vigilante Privado"),
                    ("GUARDIA_DE_SEGURIDAD", "Guardia de Seguridad"),
                    ("ENCARGADO_DE_SEGURIDAD", "Encargado de Seguridad"),
                    ("SUPERVISOR_DE_SEGURIDAD", "Supervisor de Seguridad"),
                    ("JEFE_DE_SEGURIDAD", "Jefe de Seguridad"),
                    ("ASESOR_DE_SEGURIDAD", "Asesor de Seguridad"),
                    (
                        "CAPACITADOR_DE_SEGURIDAD_PRIVADA",
                        "Capacitador de Seguridad Privada",
                    ),
                    (
                        "INSTALADOR_TECNICO_DE_SEGURIDAD",
                        "Instalador Técnico de Seguridad",
                    ),
                    ("OPERADOR_DE_CCTV_Y_ALARMAS", "Operador de CCTV y Alarmas"),
                ],
                default="GUARDIA_DE_SEGURIDAD",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="accesotestpersona",
            name="cargo",
            field=models.CharField(
                choices=[
                    ("NOCHERO", "Nochero"),
                    ("RONDIN", "Rondín"),
                    ("PORTERO", "Portero"),
                    ("CONSERJE", "Conserje"),
                    ("VIGILANTE_PRIVADO", "Vigilante Privado"),
                    ("GUARDIA_DE_SEGURIDAD", "Guardia de Seguridad"),
                    ("ENCARGADO_DE_SEGURIDAD", "Encargado de Seguridad"),
                    ("SUPERVISOR_DE_SEGURIDAD", "Supervisor de Seguridad"),
                    ("JEFE_DE_SEGURIDAD", "Jefe de Seguridad"),
                    ("ASESOR_DE_SEGURIDAD", "Asesor de Seguridad"),
                    (
                        "CAPACITADOR_DE_SEGURIDAD_PRIVADA",
                        "Capacitador de Seguridad Privada",
                    ),
                    (
                        "INSTALADOR_TECNICO_DE_SEGURIDAD",
                        "Instalador Técnico de Seguridad",
                    ),
                    ("OPERADOR_DE_CCTV_Y_ALARMAS", "Operador de CCTV y Alarmas"),
                ],
                default="GUARDIA_DE_SEGURIDAD",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
