# Generated by Django 5.0.2 on 2024-06-02 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0012_accesotest_cargo_predefinido_accesotestpersona_cargo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "texto",
                    models.TextField(
                        help_text='Se intercalará en la frase "Encontrándole <texto> para realizar las funciones de..."'
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_posibles",
                        to="tests.test",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de evaluación",
                "verbose_name_plural": "Resultados de evaluación",
                "unique_together": {("test", "nombre")},
            },
        ),
    ]
