# Generated by Django 5.0.2 on 2024-06-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0013_resultadoevaluacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultadoevaluacion",
            name="texto",
            field=models.TextField(),
        ),
    ]
