# Generated by Django 5.0.2 on 2024-06-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0014_alter_resultadoevaluacion_texto"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="fecha_emision",
            field=models.DateField(null=True),
        ),
    ]
