# Generated by Django 5.0.2 on 2024-06-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0015_resultado_fecha_emision"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultado",
            name="resultado",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
