# Generated by Django 5.0.2 on 2024-06-10 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0016_resultado_resultado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultado",
            name="resultado",
        ),
        migrations.AddField(
            model_name="resultado",
            name="resultado_test",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="tests.resultadoevaluacion",
            ),
        ),
    ]
